#!/bin/bash


OPTIONS="\
  Main\n\
 Web Browsers 1\n\
 Web Browsers 2\n\
  Documents and Files\n\
 Shell Apps\n\
  Multi Media\n\
 Tools\n\
 Games\n\
 Network\n\
 Desktop"

LAUNCHER="rofi -hide-scrollbar -m -3 -width 13 -dmenu -i -p Go-To-Workspace~~> "

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval $1
        ;;
             )
        i3-msg workspace  1:
        ;;
             )
        i3-msg workspace  2:
        ;;
             )
        i3-msg workspace  3:
        ;;
             )
        i3-msg workspace  4:
        ;;
            )
        i3-msg workspace  5:
        ;;
             )
        i3-msg workspace  6:  
        ;;
             )
        i3-msg workspace  7:
        ;;
             )
        i3-msg workspace  8:
        ;;
             )
        i3-msg workspace  9:
        ;;
             )
        i3-msg workspace  10:
        ;;
      *)
        ;;
    esac
fi